### PR TITLE
Use float_to_binary [:short] if available

### LINKED ISSUE #134: Memory usage spike during `Jason.encode`
I have a production system which builds a dynamic map of trace data, basically a deeply nested structure of lists, maps, integers, strings and decimals and it saves them to a `jsonb` field. Under the hood Ecto is using `Jason` to encode this list into a JSON string and I'm seeing a case where encoding a structure is using a surprising amount of memory.

If I encode it with a lot of memory available I get a final `byte_size` of ~98MB, but if I set a maximum heap space of 2GB I end up crashing the process while encoding it. So at some point during the encoding process we are using over 2GB of heap space to encode a 98MB string of json.

In the examples below I stashed the nested structure in an agent so I can get back to the data easily and test with fresh iex processes. The trace data contains some sensitive information, but I can generate an anonymized version of it to help with debugging if we want to dig deeper.

### Example Showing 2GB of Heap Usage

```
Interactive Elixir (1.12.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(spiff@10.60.5.17)1> {env, obligations} = Agent.get(pid("0.26285.21"), fn data -> data end); nil
nil
iex(spiff@10.60.5.17)4> Process.info(self(), :memory)
{:memory, 367926328}
iex(spiff@10.60.5.17)5> max_heap_words = div(2 * 1024 * 1024 * 1024, :erlang.system_info(:wordsize))
268435456
iex(spiff@10.60.5.17)6> Process.flag(:max_heap_size, max_heap_words)
%{error_logger: true, kill: true, size: 0}
iex(spiff@10.60.5.17)9> Jason.encode(obligations); nil

22:36:23.617 [error]      Process:            #PID<8985.27770.21> on node :"spiff@10.60.5.17"
     Context:            maximum heap size reached
     Max Heap Size:      268435456
     Total Heap Size:    270188606
     Kill:               true
     Error Logger:       true
     Message Queue Len:  0
     GC Info:            [
  old_heap_block_size: 95360811,
  heap_block_size: 174828154,
  mbuf_size: 1990542,
  recent_size: 65783490,
  stack_size: 360,
  old_heap_size: 0,
  heap_size: 77476442,
  bin_vheap_size: 3352,
  bin_vheap_block_size: 46422,
  bin_old_vheap_size: 0,
  bin_old_vheap_block_size: 46422
]
```

### Example Showing the Final JSON size with a higher heap limit

```
Interactive Elixir (1.12.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(spiff@10.60.5.17)1> max_heap_words = div(4 * 1024 * 1024 * 1024, :erlang.system_info(:wordsize))
536870912
iex(spiff@10.60.5.17)2> Process.flag(:max_heap_size, max_heap_words)
%{error_logger: true, kill: true, size: 0}
iex(spiff@10.60.5.17)3> {env, obligations} = Agent.get(pid("0.26285.21"), fn data -> data end); nil
nil
iex(spiff@10.60.5.17)4> Jason.encode!(obligations) |> byte_size()
103524838
```

### PR DESCRIPTION
**Pull request by michalmuskala**
Closes #134

### CODE REVIEW

**Comment by michalmuskala** [comment]
In my simple benchmarks for the float-heavy dataset `Canada` the runtime goes from 14.87 ms (on par with `jiffy`) and 33.59 MB memory use, to 7.81 ms (~2x faster than `jiffy`) and 9.22 MB memory use.

**Comment by shahryarjb** [comment]
Dear @michalmuskala Can I ask a question of this update?!
https://github.com/michalmuskala/jason/blob/10f8ef2a0a96287eb821ca21d8ac20f8adc2142c/lib/encode.ex#L130-L147

I am wondering why you did not write `has_short_format` in a function? Or inside the float function?
```elixir
  has_short_format = try do
    :erlang.float_to_binary(1.0, [:short])
  catch
    _, _ -> false
  else
    _ -> true
  end

  @spec float(float) :: iodata
  if has_short_format do
    def float(float) do
      :erlang.float_to_binary(float, [:short])
    end
  else
    def float(float) do
      :io_lib_format.fwrite_g(float)
   end
  end
```

Thank you

**Comment by mmmries** [comment]
❤️ 💛 💙 💚 💜 Wohoo! Thanks @michalmuskala

**Comment by lpil** [comment]
@shahryarjb Because outside of the function it is evaluated once at compile time and as such there is no performance cost to the check.

**Pull request merged**
