### PR TITLE
Add term_to_binary and binary_to_term to benchmarks

### PR DESCRIPTION
**Pull request by ckampfe**
Hi there, and thanks for the library!

I just wanted to take a stab at this one: https://github.com/michalmuskala/jason/issues/21

You may have a different approach in mind, so please, let me know. Thanks!

### CODE REVIEW

**Comment by mbenatti** [comment]
@ckampfe I'm playing with your code.

I got 

```
$ mix run bench/encode.exs
** (File.Error) could not read file "/home/m/workspace/jason/bench/data/github.json": no such file or directory
    (elixir) lib/file.ex:310: File.read!/1
    bench/encode.exs:41: anonymous fn/3 in :elixir_compiler_1.__FILE__/1
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    bench/encode.exs:39: (file)
    (elixir) lib/code.ex:677: Code.require_file/2
```

**Comment by ckampfe** [comment]
@mbenatti you're absolutely right, and thanks for noticing. Fixed in e7ab139

**Comment by michalmuskala** [comment]
Sorry for a late review.

What if we kept the jobs and inputs separate? It gives nicer reports that way.

I think it should be possible to do something like:

```elixir
decode_jobs = %{
  "Jason" => fn {json, _} -> Jason.decode!(json) end,
  "Poison" => fn {json, _} -> Poison.decode!(json) end,
  # ...
  "term_to_binary" => fn {_, etf} -> :erlang.binary_to_term(etf) end
}

# ...

read_data = fn (name) ->
  file = 
    name
    |> String.downcase
    |> String.replace(~r/([^\w]|-|_)+/, "-")
    |> String.trim("-")

  json = File.read!(Path.expand("data/#{file}.json", __DIR__))
  {json, :erlang.term_to_bianry(Jason.decode!(json))}
end

# ...

inputs = for name <- decode_inputs, into: %{}, do: {name, read_data.(name)}
```

**Comment by ckampfe** [comment]
@michalmuskala no problem! I like your way. I'll do my best to get this fixed up and pushed by this weekend. Thanks again

**Comment by ckampfe** [comment]
@michalmuskala Updated in response to your feedback.

**Comment by michalmuskala** [comment]
Thank you! :heart:

**Pull request merged**
