### PR TITLE
vendor Jason to prevent conflicts

### PR DESCRIPTION
**Pull request by axelson**
This prevents module conflicts with the user's version of Jason since both are loaded into the same beam instance (at least until #253) is addressed.

Functionally this was simply replacing `:jason` => `:jason_vendored` and `Jason` with `JasonVendored`. I only skipped the changelog (for no good reason) and the `bench` directory data.

Note: I plan to leave this PR open even though this branch is used by elixir-ls. I think that will facilitate seeing the changes as compared to the upstream Jason library. If we need to update to a new version of Jason the plan is to rebase this branch on top of the upstream changes (or just redo the changes).

This also formats the code which is another reason to just redo the changes.

### CODE REVIEW

**Comment by axelson** [comment]
references:
* https://github.com/JakeBecker/elixir-ls/issues/97#issuecomment-406243067
* https://github.com/elixir-lsp/elixir-ls/issues/253

**Comment by axelson** [comment]
Sorry, didn't mean to submit this PR here! Was meant to be directly against https://github.com/elixir-lsp/jason

**Comment by michalmuskala** [comment]
I think long-term it should be possible to do a small script doing the re-writing. I don't think there's any dynamic shenanigans in Jason that would make that difficult

**Comment by axelson** [comment]
Yeah, it was very straightforward. If I get sufficiently annoyed with staying up to date then I'll write a script :)

**Pull request closed without merging**
